---
- name: Satellite Configure
  hosts: satellite[0] # All API driven, hit the main satellite server
  gather_facts: no 
  connection: local

  collections:
    - theforeman.foreman

  tasks:

  - name: GIT export - create temporary git repository directory
    tempfile:
      state: directory
    register: git_root_dir

  - name: GIT export - Clone existing repository to {{ git_root_dir.path }}
    shell: |
      cd {{ git_root_dir.path }}
      git clone {{ import_git_url }} repo
      cd repo
      git checkout {{ import_git_branch }}

  - name: fail
    fail:

  - name: satellite settings | common settings
    theforeman.foreman.setting:
      username: "{{ satellite_admin_username }}"
      password: "{{ satellite_admin_password }}"
      server_url: "{{ satellite_server_url }}"
      name: "{{ item.name }}"
      value: "{{ item.value }}"
    with_items:
      - "{{ satellite_settings }}"
