---
- hosts: satellite[0]
  gather_facts: no
  connection: local
  
  tasks:
    - name: Run Import Role
      include_role:
        name: ansible-role-satellite-configuration-import
      run_once: true
      vars:
        git_url: '{{ export_git_url }}'
        git_push_branch: '{{ export_git_branch }}'
        sat_api_password: '{{ satellite_admin_password }}'
        sat_api_user: '{{ satellite_admin_username }}'
        curl_validate_certs: false
