satellite_manifest_uuid: e3903846-7625-4eef-82c0-0c85d8d2314
satellite_location: AWS
satellite_fqdn: rhsatred.EXAMPLE.com
satellite_org: Example_Global
capsule_ak: capsule-ak
capsules_vip: redsat.EXAMPLE.com
